final Map<String, List<String>> regions = {
  'NCR': [
    'Manila City',
    'Caloocan City',
    'Las Pinas City',
    'Makati City',
    'Malabon City',
    'Mandaluyong City',
    'Marikina City',
    'Muntinlupa City',
    'Navotas City',
    'Paranaque City',
    'Pasay City',
    'Pasig City',
    'Quezon City',
    'San Juan City',
    'Taguig City',
    'Valenzuela City',
    'Pateros City',
  ],
  'Region IV-B': [
    'Marinduque',
    'Occidental Mindoro',
    'Oriental Mindoro',
    'Palawan',
    'Romblon',
  ],
  'Region I': [
    'Ilocos Norte'
        'Ilocos Sur',
    'La Union',
    'Pangasinan',
  ],
  'Region II': [
    'Batanes',
    'Cagayan',
    'Isabela',
    'Nueva Vizcaya',
    'Quirino',
  ],
  'Region III': [
    'Aurora',
    'Bataan',
    'Bulacan',
    'Nueva Ecija',
    'Pampanga',
    'Tarlac',
    'Zambales',
  ],
  'Region IV-A': [
    'Batangas',
    'Cavite',
    'Laguna',
    'Quezon',
    'Rizal',
  ],
  'Region V': [
    'Albay',
    'Camarines Norte',
    'Camarines Sur',
    'Catanduanes',
    'Masbate',
    'Sorsogon',
  ],
  'Region VI': [
    'Aklan',
    'Antique',
    'Capiz',
    'Guimaras',
    'Iloilo',
    'Negros Occidental',
  ],
  'Region VII': [
    'Bais',
    'Bayawan',
    'Bogo',
    'Canlaon',
    'Carcar',
    'Cebu',
    'Danao',
    'Dumaguete',
    'Guihulngan',
    'Lapu-Lapu',
    'Mandaue',
    'Naga',
    'Tagbilaran',
    'Talisay',
    'Tanjay',
    'Toledo',
    'Negros Oriental'
  ],
  'Region VIII': [
    'Biliran',
    'Eastern Samar',
    'Leyte',
    'Northern Samar',
    'Samar',
    'Southern Leyte',
  ],
  'Region IX': [
    'Zamboanga del Norte',
    'Zamboanga del Sur',
    'Zamboanga Sibugay',
  ],
  'Region X': [
    'Bukidnon',
    'Camiguin',
    'Lanao Del Norte',
    'Misamis Occidental',
    'Misamis Oriental',
  ],
  'Region XI': [
    'Davao De Oro',
    'Davao Del Norte',
    'Davao Del Sur',
    'Davao Occidental',
    'Davao Oriental',
    'Compostela Valley'
  ],
  "Region XII": [
    'Cotabato',
    'Sarangani',
    'South Cotabato',
    'Sultan Kudarat',
  ],
  'Region XIII': [
    'Agusan Del Norte',
    'Agusan Del Sur',
    'Dinagat Islands',
    'Surigao Del Norte',
    'Surigao Del Sur',
  ],
  'CAR': [
    'Abra',
    'Apayao',
    'Benguet',
    'Ifugao',
    'Kalinga',
    'Mountain Province',
  ],
  'BARMM': [
    'Lanao Del Sur',
    'Maguindanao',
    'Sulu',
    'Tawi-Tawi',
  ],
  'For Validation': ['China', 'For Validation']
};
