final Map<String, List<String>> regions = {
  'NCR': [
    'Manila',
    'Caloocan',
    'Las Pinas',
    'Makati',
    'Malabon',
    'Mandaluyong',
    'Marikina',
    'Muntinlupa',
    'Navotas',
    'Paranaque',
    'Pasay',
    'Pasig',
    'Quezon City',
    'San Juan',
    'Taguig',
    'Valenzuela',
    'Pateros',
  ],
  'Region IV-B': [
    'Marinduque',
    'Occidental Mindoro',
    'Oriental Mindoro',
    'Palawan',
    'Romblon',
  ],
  'Region I': [
    'Ilocos Norte'
        'Ilocos Sur',
    'La Union',
    'Pangasinan',
  ],
  'Region II': [
    'Batanes',
    'Cagayan',
    'Isabela',
    'Nueva Vizcaya',
    'Quirino',
  ],
  'Region III': [
    'Aurora',
    'Bataan',
    'Bulacan',
    'Nueva Ecija',
    'Pampanga',
    'Tarlac',
    'Zambales',
  ],
  'Region IV-A': [
    'Batangas',
    'Cavite',
    'Laguna',
    'Quezon',
    'Rizal',
  ],
  'Region V': [
    'Albay',
    'Camarines Norte',
    'Camarines Sur',
    'Catanduanes',
    'Masbate',
    'Sorsogon',
  ],
  'Region VI': [
    'Aklan',
    'Antique',
    'Capiz',
    'Guimaras',
    'Iloilo',
    'Negros Occidental',
  ],
  'Region VII': [
    'Bais',
    'Bayawan',
    'Bogo',
    'Canlaon',
    'Carcar',
    'Cebu City',
    'Danao',
    'Dumaguete',
    'Guihulngan',
    'Lapu-Lapu',
    'Mandaue',
    'Naga',
    'Tagbilaran',
    'Talisay',
    'Tanjay',
    'Toledo',
  ],
  'Region VIII': [
    'Biliran',
    'Eastern Samar',
    'Leyte',
    'Northern Samar',
    'Samar',
    'Southern Leyte',
  ],
  'Region IX': [
    'Zamboanga del Norte',
    'Zamboanga del Sur',
    '	Zamboanga Sibugay',
  ],
  'Region X': [
    'Bukidnon',
    'Camiguin',
    'Lanao Del Norte',
    'Misamis Occidental',
    'Misamis Oriental',
  ],
  'Region XI': [
    'Davao De Oro',
    'Davao Del Norte',
    'Davao Del Sur',
    'Davao Occidental',
    'Davao Oriental',
  ],
  "Region XII": [
    'Cotabato',
    'Sarangani',
    'South Cotabato',
    'Sultan Kudarat',
  ],
  'Region XIII': [
    'Agusan Del Norte',
    'Agusan Del Sur',
    'Dinagat Islands',
    'Surigao Del Norte',
    'Surigao Del Sur',
  ],
  'BARMM': [
    'Isabela',
    'Lanao Del Sur',
    'Maguindanao',
    'Sulu',
    'Tawi-Tawi',
  ],
  'For Validation': ['For Validation'],
  'Others': ['China']
};
